LangString addOrReinstall ${LANG_POLISH} "Dodaj lub zainstaluj ponownie składniki"
LangString alreadyInstalled ${LANG_POLISH} "Aplikacja jest już zainstalowana"
LangString alreadyInstalledLong ${LANG_POLISH} "${PRODUCTNAME} ${VERSION} jest już zainstalowany. Wybierz działanie i kliknij Dalej."
LangString appRunning ${LANG_POLISH} "Super Clipboard jest uruchomiony. Zakończ aplikację w trayu i spróbuj ponownie."
LangString appRunningOkKill ${LANG_POLISH} "Super Clipboard jest uruchomiony.$\nKliknij OK, aby zakończyć jego proces."
LangString chooseMaintenanceOption ${LANG_POLISH} "Wybierz działanie."
LangString choowHowToInstall ${LANG_POLISH} "Wybierz sposób instalacji ${PRODUCTNAME}."
LangString createDesktop ${LANG_POLISH} "Utwórz skrót na pulpicie"
LangString dontUninstall ${LANG_POLISH} "Nie odinstalowuj"
LangString dontUninstallDowngrade ${LANG_POLISH} "Nie odinstalowuj (starsza wersja wymaga odinstalowania bieżącej)"
LangString failedToKillApp ${LANG_POLISH} "Nie można zakończyć Super Clipboard. Zamknij aplikację i spróbuj ponownie."
LangString installingWebview2 ${LANG_POLISH} "Instalowanie WebView2…"
LangString newerVersionInstalled ${LANG_POLISH} "Zainstalowano nowszą wersję ${PRODUCTNAME}. Zalecamy jej zachowanie. Jeśli chcesz zainstalować starszą wersję, najpierw odinstaluj bieżącą."
LangString older ${LANG_POLISH} "starsza"
LangString olderOrUnknownVersionInstalled ${LANG_POLISH} "Na komputerze jest zainstalowana inna wersja ${PRODUCTNAME}. Wybierz działanie i kliknij Dalej."
LangString silentDowngrades ${LANG_POLISH} "Nie można automatycznie zainstalować starszej wersji. Użyj interfejsu instalatora.$\n"
LangString unableToUninstall ${LANG_POLISH} "Nie można odinstalować aplikacji."
LangString uninstallApp ${LANG_POLISH} "Odinstaluj ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_POLISH} "Odinstaluj przed instalacją"
LangString unknown ${LANG_POLISH} "nieznana"
LangString webview2AbortError ${LANG_POLISH} "Nie można zainstalować WebView2. Aplikacja wymaga tego składnika Microsoft. Spróbuj ponownie uruchomić instalator."
LangString webview2DownloadError ${LANG_POLISH} "Błąd pobierania WebView2: $0"
LangString webview2DownloadSuccess ${LANG_POLISH} "Pobrano instalator WebView2."
LangString webview2Downloading ${LANG_POLISH} "Pobieranie instalatora WebView2…"
LangString webview2InstallError ${LANG_POLISH} "Instalacja WebView2 zakończyła się błędem: $1"
LangString webview2InstallSuccess ${LANG_POLISH} "Zainstalowano WebView2."
LangString deleteAppData ${LANG_POLISH} "Usuń również dane aplikacji (historię i snippety)"
